routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

# Dashboard
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'permission:dashboard']], function() {
        Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);

        Route::get('users/select2', ['as' => 'users.select2', 'uses' => 'UserController@select2']);
        Route::resource('users', 'UserController')->middleware('permission:users');
        Route::resource('teams', 'TeamController')->middleware('permission:teams');

        Route::resource('levels', 'LevelController')->middleware('permission:levels');
        Route::resource('cycles', 'CycleController')->middleware('permission:cycles');
        Route::resource('grades', 'GradeController')->middleware('permission:grades');
        Route::resource('branches', 'BranchController')->middleware('permission:branches');
        Route::resource('lines', 'LineController')->middleware('permission:lines');
        Route::resource('expects', 'ExpectController')->middleware('permission:expects');
        Route::resource('specifics', 'SpecificController')->middleware('permission:specifics');
        Route::resource('skills', 'SkillController')->middleware('permission:skills');
        Route::resource('descriptions', 'DescriptionController')->middleware('permission:descriptions');
        Route::resource('subjects',  'SubjectController')->middleware('permission:subjects');

        Route::resource('rivens', 'RivenController')->middleware('permission:rivens');
        Route::resource('cikls',  'CiklController')->middleware('permission:cikls');
        Route::resource('notes',  'NoteController')->middleware('permission:notes');
        Route::resource('classes',  'ClassController')->middleware('permission:classes');
        Route::resource('galuzes',  'GaluzController')->middleware('permission:galuzes');
        Route::resource('zors',  'ZorController')->middleware('permission:zors');
        Route::resource('zmists',  'ZmistController')->middleware('permission:zmists');
        Route::resource('kors',  'KorController')->middleware('permission:kors');
        Route::resource('umenies',  'UmenieController')->middleware('permission:umenies');
        Route::resource('galuznotes',  'GaluznoteController')->middleware('permission:galuznotes');
        Route::resource('_subjects',  '_SubjectController')->middleware('permission:_subjects');

        Route::post('/newprograms/changeStatus/{id}',     ['as'=>'newprograms.changeStatus',  'uses'=>'NewprogramController@changeStatus']);
        Route::get('/newprograms/list/{type}', ['as'=>'newprograms.list', 'uses'=>'NewprogramController@list']);
        Route::resource('newprograms', 'NewprogramController');
        Route::post('/newplans/changeStatus/{id}',     ['as'=>'newplans.changeStatus',  'uses'=>'NewplanController@changeStatus']);
        Route::resource('newplans', 'NewplanController');
        Route::post('/materials/changeStatus/{id}',     ['as'=>'materials.changeStatus',  'uses'=>'MaterialController@changeStatus']);
        Route::resource('materials', 'MaterialController');
        Route::post('/newpackages/changeStatus/{id}',     ['as'=>'newpackages.changeStatus',  'uses'=>'NewpackageController@changeStatus']);
        Route::resource('newpackages', 'NewpackageController');
        Route::post('/layouts/changeStatus/{id}',     ['as'=>'layouts.changeStatus',  'uses'=>'LayoutController@changeStatus']);
        Route::resource('layouts', 'LayoutController');

        Route::resource('pages', 'PageController')->middleware('permission:pages');
        Route::resource('posts', 'PostController')->middleware('permission:posts');

        Route::resource('roles', 'RoleController', ['except' => 'show'])->middleware('permission:vocabularies');
        Route::resource('permissions', 'PermissionController', ['except' => 'show'])->middleware('permission:vocabularies');
        Route::get('institutions/select2', ['as' => 'institutions.select2', 'uses' => 'InstitutionController@select2']);
        Route::resource('institutions', 'InstitutionController', ['only' => ['index', 'store', 'show', 'data']])->middleware('permission:institutions');
        Route::resource('creates', 'CreateController', ['except' => 'show'])->middleware('permission:creates');
        Route::resource('cats', 'CatController', ['except' => 'show'])->middleware('permission:cats');
        Route::resource('tools', 'ToolController', ['except' => 'show'])->middleware('permission:tools');
        Route::resource('statuses', 'StatusController', ['except' => 'show'])->middleware('permission:statuses');
        Route::resource('stypes', 'StypeController', ['except' => 'show'])->middleware('permission:stypes');
        Route::resource('ptypes', 'PtypeController', ['except' => 'show'])->middleware('permission:ptypes');

        Route::resource('ttypes', 'TtypeController', ['except' => 'show'])->middleware('permission:ttypes');
        Route::resource('teamroles', 'TeamroleController', ['except' => 'show'])->middleware('permission:teamroles');
        Route::resource('periods', 'PeriodController', ['except' => 'show'])->middleware('permission:periods');

        Route::match(['get', 'post'],'/options',  ['as'=>'options', 'uses'=>'AdminController@options'])->middleware('permission:options');
        Route::get('transfer', ['as' => 'transfer', 'uses' => 'AdminController@transfer'])->middleware('permission:transfer');
        Route::get('customseed', ['as' => 'customseed', 'uses' => 'AdminController@customseed'])->middleware('permission:customseed');

        # Модуль "Навчальний план"
        Route::resource('languagetypes', 'LanguagetypeController', ['except' => 'show'])->middleware('permission:languagetypes');
        Route::resource('ctypes', 'CtypeController', ['except' => 'show'])->middleware('permission:ctypes');
        Route::resource('cbranches', 'CbranchController', ['except' => 'show'])->middleware('permission:cbranches');
        Route::resource('components', 'ComponentController')->middleware('permission:components');
        Route::resource('cauthors', 'CauthorController', ['except' => 'show'])->middleware('permission:cauthors');
        Route::resource('cprograms', 'CprogramController')->middleware('permission:cprograms');
        Route::resource('cperiods', 'CperiodController', ['except' => 'show'])->middleware('permission:cperiods');
        // Route::resource('loadtypes', 'LoadtypeController', ['except' => 'show'])->middleware('permission:loadtypes');
        Route::resource('loadtemplates', 'LoadtemplateController')->middleware('permission:loadtemplates');

        # Посев данных
        Route::match(['get', 'post'],'/seeds', 'AdminController@seeds')->name('seeds')->middleware('permission:seeds');
        Route::get('/phpinfo', ['as' => 'phpinfo', 'uses' => 'AdminController@phpinfo']);

    });


# User
    Route::group(['middleware' => ['auth']], function() {
        Route::get('/profile',       ['as' => 'profile', 'uses' => 'UserController@profile']);
        Route::post('/user-change-avatar',  ['as' => 'user.change-avatar', 'uses'=>'UserController@userChangeAvatar']);
        Route::post('/user-update',  ['as' => 'user.update', 'uses'=>'UserController@user_update']);
        Route::get('/teams-select2', ['as' => 'teams-select2', 'uses' => 'UserController@teams_select2']);
        Route::get('/teams-all-select2', ['as' => 'teams-all-select2', 'uses' => 'UserController@teams_all_select2']);
        Route::get('/uteams',        ['as' => 'uteams', 'uses' => 'UserController@uteams']);

        Route::post('/apply',        ['as'=>'apply', 'uses'=>'UserController@apply']);

        Route::get('/uteam/{team_id}',    ['as' => 'uteam.info', 'uses' => 'TeamController@info']);
        Route::post('/approve/{team_id}/{user_id}', ['as'=>'uteam.approve', 'uses'=>'TeamController@approve']);
        Route::post('/remove/{team_id}/{user_id}', ['as'=>'uteam.remove', 'uses'=>'TeamController@remove']);
        Route::resource('/uteam/{team_id}/tspecifics', 'TspecificController')->middleware('teamActiveMember');

        # Программы команды
        Route::get( '/uteam/{team_id}/tnewprograms/catch/{ulayout}',['as'=>'tnewprograms.catch', 'uses'=>'TnewprogramController@catch']);
        Route::post('/uteam/{team_id}/tnewprograms/share/{ulayout}',['as'=>'tnewprograms.share', 'uses'=>'TnewprogramController@share']);
        Route::post('/uteam/{team_id}/tnewprograms/clone/{ulayout}',['as'=>'tnewprograms.clone', 'uses'=>'TnewprogramController@clone']);
        Route::post('/uteam/{team_id}/tnewprograms/send/{ulayout}', ['as'=>'tnewprograms.send',  'uses'=>'TnewprogramController@send']);
        Route::post('/uteam/{team_id}/tnewprograms/withdraw/{ulayout}', ['as'=>'tnewprograms.withdraw',  'uses'=>'TnewprogramController@withdraw']);
        Route::post( '/uteam/{team_id}/tnewprograms/createOnLayout',['as'=>'tnewprograms.createOnLayout','uses'=>'TnewprogramController@createOnLayout']);
        Route::get( '/uteam/{team_id}/getSpecifics/{id}',['as'=>'tnewprograms.getSpecifics', 'uses'=>'TnewprogramController@getSpecifics']);
        Route::get('/uteam/{team_id}/tnewprograms/list/{type}', ['as'=>'tnewprograms.list', 'uses'=>'TnewprogramController@list']);
        Route::resource('/uteam/{team_id}/tnewprograms', 'TnewprogramController')->middleware('teamActiveMember');

        # Планы команды
        Route::post('/uteam/{team_id}/tnewplans/send/{id}',     ['as'=>'tnewplans.send',  'uses'=>'TnewplanController@send']);

app/Http/Controllers/Dashboard/BranchController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreBranchRequest;

use App\Http\Controllers\Controller;
use App\Models\Branch;


class BranchController extends Controller 
{

    public function index(Request $request)
    {
        return view('dashboard.branches.index', []);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.branches.form', [
                'model' => new Branch,
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBranchRequest $request)
    {
        $array = [
                'name' => $request->name,
                'marking' => $request->marking,
                'color' => $request->color,
                'content' => $request->content,
            ];
        $model = Branch::create($array);
        return response([
            'message' => __('MAIN.MESSAGE.CREATED'),
            'exitURL' => route('branches.index'),
            'formAction' => route('branches.update', $model->id),
        ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Branch::findOrFail($id);
        return view('dashboard.branches.form', [
                'model' => $model,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreBranchRequest $request, $id)
    {
        $model = Branch::findOrFail($id);
        $array = [
                'name' => $request->name,
                'marking' => $request->marking,
                'color' => $request->color,
                'content' => $request->content,
            ];
        $model->update($array);
        return response([
            'message' => __('MAIN.MESSAGE.UPDATED'),
            'exitURL' => route('branches.index'),
            'formAction' => route('branches.update', $model->id),
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $model = Branch::findOrFail($id);
        $model->delete();
        return response([], 200);
    }


    /**
     * Get list of data for datatable.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function data(Request $request)
    {
        return json_encode( Branch::getListForDatatable($request) );
    }

}

app/Http/Controllers/Dashboard/CatController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreCatRequest;

use App\Http\Controllers\Controller;
use App\Cat;


class CatController extends Controller 
{

    public function index(Request $request)
    {
        return view('dashboard.cats.index', []);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.cats.form', [
                'model' => new Cat,
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCatRequest $request)
    {
        $array = [
                'name_cat' => $request->name_cat,
                'slug_cat' => $request->slug_cat,
            ];
        $model = Cat::create($array);
        return response([
            'message' => __('MAIN.MESSAGE.CREATED'),
            'exitURL' => route('cats.index'),
            'formAction' => route('cats.update', $model->id_cat),
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('cats');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Cat::findOrFail($id);
        return view('dashboard.cats.form', [
                'model' => $model,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCatRequest $request, $id)
    {
        $model = Cat::findOrFail($id);
        $array = [
                'name_cat' => $request->name_cat,
                'slug_cat' => $request->slug_cat,
            ];
        $model->update($array);
        return response([
            'message' => __('MAIN.MESSAGE.UPDATED'),
            'exitURL' => route('cats.index'),
            'formAction' => route('cats.update', $model->id_cat),
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $model = Cat::findOrFail($id);
        $model->delete();
        return response([], 200);
    }


    /**
     * Get list of data for datatable.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function data(Request $request)
    {
        return json_encode( Cat::getListForDatatable($request) );
    }

}

resources/views/dashboard/galuzes/form.blade.php
@extends('layouts.dashboard')

@section('content')

{{ Form::model($model, [ 'url' => $model->id_galuz ? route('galuzes.update', $model->id_galuz) : route('galuzes.store'), 'method' => $model->id_galuz ? 'PUT' : 'POST', 'class' => 'ajax-form' ]) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header bg-transparent header-elements-inline">
                <h5 class="card-title">@lang('MAIN.TITLE.PARAMETERS')</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    {{ Form::label('name_galuz', __('MAIN.COLUMN.NAME'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::text('name_galuz', $model->name_galuz, array('class' => 'field form-control')) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('marking_galuz', __('MAIN.COLUMN.MARKING'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::text('marking_galuz', $model->marking_galuz, array('class' => 'field form-control')) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('color_galuz', __('MAIN.COLUMN.MARKING'), ['class'=>'small text-muted font-italic col-md-4 col-form-label']) }}
                    <div class="col-md-8">
                        {{ Form::text('color_galuz', $model->color_galuz, array('class' => 'field form-control colorpicker-show-input', 'data-preferred-format' => 'hex')) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('text_galuz', __('MAIN.COLUMN.CONTENT'), ['class'=>'small text-muted font-italic col-form-label']) }}
                    {{ Form::textarea('text_galuz', (isset($model->text_galuz) ? $model->text_galuz : null), ['class' => 'editor-full field form-control', 'id' => 'editor']) }}
                </div>

            </div>
        </div>

    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-mobile-component w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">@lang('MAIN.TITLE.NAVIGATION')</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="@lang('MAIN.HINT.SAVE')"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('galuzes.index') }}" class="btn btn-danger w-50" title="@lang('MAIN.HINT.EXIT')"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}
@endsection

@section('scripts')
<script src="/js/ckeditor/ckeditor.js"></script>
<script src="/js/color/spectrum.js"></script>
<script>
    $('.colorpicker-show-input').spectrum({
        showInput: true
    });
$(document).ready(function(){
    $('.editor-full').each(function(e){
        CKEDITOR.replace(this.id, {
            height: 400,
            extraPlugins: 'forms'
        });
    });    
});    
</script>
@endsection

resources/views/dashboard/galuzes/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="card mb-3">

    <!-- Search panel -->
        <div class="search-panel">
            <div class="text-right">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{{route('galuzes.create')}}" title="@lang('MAIN.HINT.CREATE')"><i class="icon-file-plus"></i></a>
                    <button type="button" class="btn btn-primary datatableRefresh" title="@lang('MAIN.HINT.REFRESH')"><i class="icon-sync"></i></button>
                </div>                
                
            </div>
        </div>
    <!-- /Search panel -->

    <!-- Tabs -->
            <ul class="nav nav-tabs nav-tabs-highlight">
                <li class="nav-item"><a href="#tab-active" class="nav-link active" data-toggle="tab"><i class="icon-menu7 mr-2"></i> @lang('MAIN.TAB.ACTIVE')</a></li>
            </ul>

            <div class="tab-content">
                <!-- Active Table -->
                    <div class="tab-pane fade show active" id="tab-active">
                        <div class="table-responsive">
                            <table class="table table-bordered table-styled table-striped mb-3 w-100 datatable" id="datatableActive">
                                <thead class="bg-indigo">
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('MAIN.COLUMN.NAME')</th>
                                        <th>@lang('MAIN.COLUMN.MARKING')</th>
                                        <th>@lang('MAIN.COLUMN.COLOR')</th>
                                        <th>@lang('MAIN.COLUMN.ACTIONS')</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                <!-- /Active Table -->
            </div>
    <!-- /Tabs -->

</div>
@endsection

@section('scripts')
<script src="/js/datatables/datatables.min.js"></script>
<script>
    var language = {"url": "/js/datatables/languages/ukrainian.json"};
    var pageLength = {{ isset(auth()->user()->options->datatablePageLength) ? auth()->user()->options->datatablePageLength : 10 }};

    var columns = [
            {"data":"id"},
            {"data":"name"},
            {"data":"marking"},
            {"data":"color","searchable":false,"orderable":false},
            {"data":"actions","searchable":false,"orderable":false}
        ];
    var columnDefs = [
            { "targets": 0, "className": "text-center", },
            { "targets": 2, "className": "text-center", },
            { "targets": 3, "className": "text-center", },
            { "targets": 4, "className": "text-center", },
        ];


    var tableActive = $("#datatableActive").DataTable({
        autoWidth : true,
        responsive: true,
        processing: true,
        serverSide: true,
        pageLength: pageLength,
        bSortCellsTop: true,
        order: [[ 0, "desc" ]],
        ajax: {
            url: "{{route('galuzes.data')}}",
            dataType: "json",
            type: "POST",
            data: {"_token":"{{ csrf_token() }}", "table":"active"},
        },
        columns:columns,
        columnDefs: columnDefs,
        language: language,
    });
</script>
@endsection